In [1]:
import tensorflow as tf

/Users/jDB/.pyenv/versions/3.6.5/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
a = tf.constant([1, 2, 3], name="a")
b = tf.constant([4, 5, 6], name="b")
c = tf.add(a, b)

In [3]:
sess = tf.Session()
sess.run(c)

array([5, 7, 9], dtype=int32)

In [4]:
d = tf.constant([[1, 2], [3, 4], [5, 6]], name="d")
e = tf.constant([[1, 2, 3], [4, 5, 6]], name="e")
# 行列の積
f = tf.matmul(d, e)

In [5]:
print(d.shape)

(3, 2)


In [6]:
print(e.shape)

(2, 3)


In [7]:
print(f.shape)

(3, 3)


In [8]:
print(sess.run(f))

[[ 9 12 15]
 [19 26 33]
 [29 40 51]]
